---
title: "Data Import"
author: "Jessica Lavery"
date: "9/17/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Load in a dataset
```{r load_dset}
# be careful to use read_csv (reads in as a tibble) instead of read.csv (reads in data frame)
litters_data = read_csv(file = "./data/FAS_litters.csv")
```

# Clean up variable names
```{r}
# view existing variable names
names(litters_data)

# clean up variable names
litters_data <-  janitor::clean_names(litters_data)

# view new variable names
names(litters_data)
```

# Inspect data
```{r}
# View(litters_data)

# check first few rows of the data
litters_data

# check last few rows of the data
tail(litters_data, 5)

# skim the data
skimr::skim(litters_data)
```

# Read in pups dataset
```{r}
pups_data <- read_csv("./data/FAS_pups.csv")
```

# Clean pups variable names
```{r}
# look at existing variable names
names(pups_data)

# clean variable names
pups_data = janitor::clean_names(pups_data)

# look at new variable names
names(pups_data)
```

# Inspect the pups data
```{r}
# look at first few rows
pups_data

# look at last few rows
tail(pups_data, n = 10)

# skim the data
skimr::skim(pups_data)
```

# Compare read in with base R
```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")
```

# Read Excel files
```{r}
library(readxl)

mlb11_data <- read_excel("./data/mlb11.xlsx", n_max = 20)

# variable names are clean, don't need to use janitor::clean_names
head(mlb11_data, 5)
```

# Read in a SAS dataset
```{r}
library(haven)

pulse_data = read_sas("./data/public_pulse_data.sas7bdat")

#variable names are mixed case, want to clean
head(pulse_data, 5)

pulse_data = janitor::clean_names(pulse_data)

names(pulse_data)
```




